### ISSUE TITLE
Do you think it would be possible to add compression?

### ISSUE THREAD

**Issue by dontbanmeplz** [MeViMo/youbit#5]
Like a red pixel is 00 and a green pixel is 11

**Comment by MeViMo** [comment]
This is already present, except not with colors because of reasons explained [here](https://github.com/MeViMo/youbit#why-no-colors).
YouBit can encode videos with 1 bit of information per pixel (the default), 2 or 3. [This feature is explained here](https://github.com/MeViMo/youbit#what-is-bpp).

You can try out a bpp of 2 by also enabling the 'zero_frame' option. A bpp of 3 will not work unless you find a way to make it work that I have not yet thought of.
